### ISSUE TITLE
Original error was: DLL load failed: 找不到指定的模块。 # 

### ISSUE THREAD

**Issue by wuxiaolianggit** [iwanao731/DeformationTransferForMaya#1]
Excuse me, how to solve this problem?

Original error was: DLL load failed: 找不到指定的模块。 #

**Comment by wuxiaolianggit** [comment]
the problem will happen when install numpy and scipy for my Maya environemnt. @iwanao731

**Comment by iwanao731** [comment]
@wuxiaolianggit 

Hi. Thanks for message.
My environment is Maya 2018 on Windows 10 64bit.

I don't know the reason for the error status.
For your try, I have a Dropbox paper's memo when I installed numpy and scipy on my Maya environment. Unfortunately it is Japanese, but I hope you can translate to your preferred language.
https://paper.dropbox.com/doc/Inverse-Rig-Mapping-Project--AzOTvHJRvO8lt6Vu9Zs75reJAQ-XvfPG0yAgR4vHSDo3LHJP

If you have any trouble, please reply anytime.
